Repository jupyterlab-contrib/jupyterlab-filesystem-access, pull requests merged in 2022-04, with the labels that each got.

#4 Add disclaimer to README.md
  README.md
Labels: documentation

#5 Basic support for saving a file
  src/drive.ts
  src/index.ts
Labels: enhancement

#6 Rename to `jupyterlab-filesystem-access`
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .gitignore
  .prettierignore
  MANIFEST.in
  README.md
  RELEASE.md
  install.json
  jupyterlab_filesystem_access/__init__.py
  jupyterlab_filesystem_access/_version.py
  package.json
  pyproject.toml
  setup.py
  src/index.ts
Labels: maintenance

#7 Reset version
  package.json
Labels: maintenance

#8 Automated Changelog Entry for 0.1.0 on main
  CHANGELOG.md
Labels: documentation

#9 Fix saving Notebooks
  src/drive.ts
Labels: bug

#10 Automated Changelog Entry for 0.1.1 on main
  CHANGELOG.md
Labels: documentation

#11 Add support opening subdirs
  src/drive.ts
  src/index.ts
Labels: enhancement

#12 Automated Changelog Entry for 0.2.0 on main
  CHANGELOG.md
Labels: documentation

#16 Automated Changelog Entry for 0.3.0 on main
  CHANGELOG.md
Labels: documentation

#25 Update links to point to the new repo
  CHANGELOG.md
  README.md
  package.json
Labels: documentation

#27 Add docs
  .readthedocs.yaml
  MANIFEST.in
  README.md
  docs/Makefile
  docs/environment.yml
  docs/make.bat
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation

#28 Update documentation title
  docs/source/index.rst
Labels: documentation

#29 Update README with docs and lite links
  README.md
Labels: documentation

#30 Automated Changelog Entry for 0.4.0 on main
  CHANGELOG.md
Labels: documentation
