Repository jupyterlab-contrib/jupyterlab-filesystem-access, pull requests merged in 2022-06, with the labels that each got.

#34 Implement rename and copy
  MANIFEST.in
  package.json
  schema/plugin.json
  src/drive.ts
  src/index.ts
Labels: enhancement

#35 Automated Changelog Entry for 0.5.0 on main
  CHANGELOG.md
Labels: documentation

#37 Run CI on Windows + Use micromamba
  .github/workflows/build.yml
  MANIFEST.in
  environment.yml
Labels: maintenance

#39 Automated Changelog Entry for 0.5.1 on main
  CHANGELOG.md
Labels: documentation
